Main svc
PriestSexist/java-explore-with-me pull request #3
Opened 2023-12-05 13:27 UTC by PriestSexist

2023-12-07 07:40 UTC, LexLippi requested changes
Привет!

Непплохая работа!

НО некоторые ошибки являются повторяющимися, я мог откомментировать их не все, чтобы не перегружать MR,  но ты поправь все которые обнаружишь.

Желаю удачи!

2023-12-07 07:40 UTC, LexLippi commented on stat-server/stat-client/src/main/java/ru/practicum/statclient/StatClient.java
> +        if (Objects.nonNull(uris) && !uris.isEmpty()) {
Вторая часть условия не нужна, если список пустой, то `pathBuilder` просто ничего не заапендит

2023-12-07 07:40 UTC, LexLippi commented on ewm-server/src/main/java/ru/practicum/ewmserver/user/storage/UserRepository.java
> +            "where (:ids is null or u.id in :ids) ")
В запросе может возникнуть проблема, если список идентификаторов не `null`, но пустой

2023-12-07 07:40 UTC, LexLippi commented on ewm-server/src/main/java/ru/practicum/ewmserver/user/service/AdminUserServiceImpl.java
> +        } else {
`else` не нужен

2023-12-07 07:40 UTC, LexLippi commented on ewm-server/src/main/java/ru/practicum/ewmserver/user/controller/AdminUserController.java
> +                              @RequestParam(defaultValue = "10") @Positive int size);
А есть ли смысл в этих аннотациях в рамках интерфейса?
Кажется, что это `implementation detail` и не надо тащить ее в интерфейс, если мы захотим сделать другую реализацию, она может иметь другие требования, при идентичном интерфейсе

2023-12-07 07:40 UTC, LexLippi commented on ewm-server/src/main/java/ru/practicum/ewmserver/request/service/PrivateRequestServiceImpl.java
> +            if (requestRepository.countRequestByEventIdAndStatus(eventId, RequestStatus.CONFIRMED) >= eventFromDb.getParticipantLimit()) {
Может объединить это в одно условие?

2023-12-07 07:40 UTC, LexLippi commented on ewm-server/src/main/java/ru/practicum/ewmserver/request/service/PrivateRequestService.java
> +    @Transactional(propagation = Propagation.REQUIRED)
Аналогичный вопрос про `implementation detail`

2023-12-07 07:40 UTC, LexLippi commented on ewm-server/src/main/java/ru/practicum/ewmserver/request/controller/PrivateRequestController.java
> +public interface PrivateRequestController {
Про это писал уже

2023-12-07 07:40 UTC, LexLippi commented on ewm-server/src/main/java/ru/practicum/ewmserver/event/storage/EventRepository.java
> +            "and (:category is null or e.category.id in :category) " +
Что будет если `category` - пустой список? И может ли быть такое?

2023-12-07 07:40 UTC, LexLippi commented on ewm-server/src/main/java/ru/practicum/ewmserver/event/storage/EventRepository.java
> +            "and e.paid = :paid " +
Может ли параметр `paid` быть null?

2023-12-07 14:27 UTC, PriestSexist commented on ewm-server/src/main/java/ru/practicum/ewmserver/user/storage/UserRepository.java
> +            "where (:ids is null or u.id in :ids) ")
Я в сервисе проверяю, пустой он или нет. Если пустой, то вызываю другой метод

2023-12-07 14:56 UTC, PriestSexist commented on ewm-server/src/main/java/ru/practicum/ewmserver/user/storage/UserRepository.java
> +            "where (:ids is null or u.id in :ids) ")
Данный момент обработан в UserService. Если список пустой, то я вызываю другой метод. 

![image](https://github.com/PriestSexist/java-explore-with-me/assets/69405678/0bdf07ce-820c-477b-a65e-8175fb82ab61)

2023-12-07 15:51 UTC, PriestSexist commented on ewm-server/src/main/java/ru/practicum/ewmserver/event/storage/EventRepository.java
> +            "and e.paid = :paid " +
Не может быть. При вызове метода я всегда передаю true. Но могу и передавать булево значение, потому что у меня в контроллере указано дефолтное значение

![image](https://github.com/PriestSexist/java-explore-with-me/assets/69405678/6c890dca-98a7-4b63-ab17-61b334635fdc)

2023-12-07 15:57 UTC, PriestSexist commented on ewm-server/src/main/java/ru/practicum/ewmserver/user/controller/AdminUserController.java
> +                              @RequestParam(defaultValue = "10") @Positive int size);
Без аннотаций выбрасывает ошибку. Так что, полагаю, от интерфейсов для контроллеров можно избавиться, если они работают только с implementation detail

![image](https://github.com/PriestSexist/java-explore-with-me/assets/69405678/7ac912c5-10a0-4903-9147-7ebff192b32c)

2023-12-08 07:26 UTC, LexLippi commented on ewm-server/src/main/java/ru/practicum/ewmserver/event/storage/EventRepository.java
> +            "and e.paid = :paid " +
Просто если не может быть `null`, то лучше использовать примитивы (типа `boolean`), а не их объектные аналоги

2023-12-08 07:27 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи с последним этапом диплома!

2023-12-08 09:42 UTC, merged